---
title: "Bayesian Logistic Growth Model"
author: "Luis M. Lomeli"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---


```{r, load-libraries, warning=FALSE, message=FALSE}
rm(list=ls())

library(ggplot2)
library(rstan)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
library(plyr)
library(reshape2)

RUN_STAN = TRUE  #If FALSE, then will load previously simulated samples

```


$\frac{dN}{dt}= r N(1-\frac{N}{K})$

and with initial condition

$N(t=0) = N_0$
where $r$ defines the growth rate and $K$ is the carrying capacity.
This model has analytical solution

$N(t)=\frac{K}{1+(\frac{K-N_0}{N_0})e^{-rt}}$



#Logistic model

## Foward run with fixed parameters


```{r, Logistic-forward-run, cache=TRUE}

# We choose population sizes and parameters values arbitrarily for illustration
# purposes

N0 = 0.1
K = 20
r = 1

logistic_eq = function(r, K, N0, t){
  return(K/(1 + ((K-N0)/N0)*exp(-r*t) ))
}

xfull = seq(0, 12, by=0.1)
yfull = logistic_eq(r=r, K=K, N0=N0, t=xfull)

plot(xfull, yfull)



```

```{r, Logistic-create_df, cache=T}

N0 = 0.1
K = 20
r = 1
sigma = 1.5

logistic_eq = function(r, K, N0, t){
  return(K/(1 + ((K-N0)/N0)*exp(-r*t) ))
}


x = seq(0, 12, by=1)
y = logistic_eq(r=r, K=K, N0=N0, t=x)

set.seed(12345)
ynoisy = y + rnorm(n = length(x), sd=sigma)

plot(x, ynoisy)
lines(xfull, yfull)


df_logistic = data.frame(time=x, y=ynoisy, ytrue=y)

```



# Fitting the logistic model in STAN


```{r, Logistic-STAN, cache=TRUE}
stan_data = list(N_ts = length(df_logistic$y), obs_times = df_logistic$time, 
                 y_obs = df_logistic$y, N0=N0, sigma=sigma, K=K)

if (isTRUE(RUN_STAN)){
  stan_logistic = stan(file = 'Logistic-equation.stan', data=stan_data, 
                        iter=5000, chains = 4, seed=1234)
  save(stan_logistic, file='data/Logistic_STAN.rda.gzip', compress=TRUE)
  
} else{ 
  load(file='data/Logistic_STAN.rda.gzip')
}

print(stan_logistic)
plot(stan_logistic, pars=c('r', 'sigma'))
plot(stan_logistic, pars=c('K'))
pairs(stan_logistic, pars=c('r', 'K', 'sigma'))

```



```{r, Logistic-STAN-plot, cache=TRUE}

samples = extract(stan_logistic)

# Create data frame of ODE solutions adding initial condition at the beginning of the data frame
y_checks_mean_summ = summary(stan_logistic, pars=c('y_checks_mean'))$summary


df_y_checks_mean = data.frame(median=y_checks_mean_summ[,"50%"],
                              time = df_logistic$time)
df_y_checks_mean

# Create posterior checks summary

y_checks_summ = summary(stan_logistic, pars=c('y_checks'))$summary

df_pred = data.frame(time=df_logistic$time,
                     ymin = as.numeric(y_checks_summ[,'2.5%']),
                     ymax = as.numeric(y_checks_summ[,'97.5%']),
                     ymedian = as.numeric(y_checks_summ[,'50%']),
                     ymean = as.numeric(y_checks_summ[,'mean'])
                    )
df_pred

TOT_SAMPLES = dim(samples$y_checks_mean)[1]
#Generate data frame with individual fitted lines aka spaguetti plots
TOT_SPAGUETTIS = 40
SAMPLES_ID_PLOT = sample(1:TOT_SAMPLES, TOT_SPAGUETTIS)
y_checks_mean <- adply(samples$y_checks_mean[SAMPLES_ID_PLOT,], 2)
tmp = melt(y_checks_mean)
names(tmp) = c("xid", "group", "y")
tmp <- mutate(tmp, x=df_logistic$time[xid])

# Logistic synthetic data

ggplot() +
  geom_point(data=df_logistic,
           aes(x=time, y=y), size=4, shape=4, stroke=2) +
  theme_bw() -> logistic_plot_base
print(logistic_plot_base)

# 95% Bayesian credible error bars for posterior checks

logistic_plot = logistic_plot_base +  
  geom_errorbar(data=df_pred, 
                aes(x=time, ymin=ymin, ymax=ymax)) +
  ggtitle('95% Posterior Predictive Checks')
print(logistic_plot)


#Spaghetti plots: samples of individual fitted lines
logistic_plot = logistic_plot_base +  
  geom_line(data=tmp, aes(x=x,y=y, group=group), colour="#999999", alpha=0.3)+
  ggtitle('Distribution of fitted ODE solutions')
print(logistic_plot)


# Fitted line
logistic_plot = logistic_plot_base +  
  geom_line(data = df_pred, aes(x=time, y=ymedian), size=1,
            alpha=1) +
  geom_ribbon(data=df_pred, aes(x=time, ymin=ymin, ymax=ymax),
              alpha=0.1,show.legend = FALSE)+
  ggtitle('95% Bayesian Credible Intervals and Median')
 
print(logistic_plot)


```


## Exercise: Fit the simple linear regression model to the Logistic dataset

```{r, Logistic-Exercise, cache=TRUE}

```


# Session Info
```{r}
library(utils)
sessionInfo()
```

